#version: '3'

services:

  postgresql:
    image: docker.1ms.run/library/postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  hmdm:
    build:
      context: ../
      dockerfile: hmdm-docker/Dockerfile.build
    image: registry.cn-shenzhen.aliyuncs.com/sailfish/yanxue:yanxue-hmdm-server-v5.38.6
    container_name: yanxue-hmdm-server
    ports:
      - "0.0.0.0:8081:8080"
      - "0.0.0.0:31000:31000"
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
      - ./volumes/letsencrypt:/etc/letsencrypt
      - ./volumes/hmdm-config:/usr/local/tomcat/conf/Catalina/localhost
    environment:
      SQL_HOST: postgresql
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      BASE_DOMAIN: ${BASE_DOMAIN}
      LOCAL_IP: ${LOCAL_IP}
      PROTOCOL: ${PROTOCOL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SHARED_SECRET: ${SHARED_SECRET}
      HMDM_VARIANT: ${HMDM_VARIANT}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      HMDM_URL: ${HMDM_URL}
      CLIENT_VERSION: ${CLIENT_VERSION}
      FORCE_RECONFIGURE: ${FORCE_RECONFIGURE}
    depends_on:
      - postgresql
  # 产品官网
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: registry.cn-shenzhen.aliyuncs.com/sailfish/yanxue:yanxue-website-v0.0.2
    container_name: yanxue-website
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8001
    ports:
      - "13001:3001"
    volumes:
      - ./website/src:/app/src
      - ./website/public:/app/public
